### ISSUE TITLE
How to run the project in the browser

### ISSUE THREAD

**Issue by githubvishalshah** [fluppyBot/JeromeClothiers-Sandbox#42]
Hi,

This is not actually an issue but a basic quick question. 
I would like to know how to run the project in the browser. I have downloaded the project but I am not getting how to run the project in browser. 

Can you please let me know the requirements to run the project and the full steps to run the project in browser?

**Comment by kerwinang2016** [comment]
you cannot run it in browser..

**Comment by githubvishalshah** [comment]
Thanks for your quick response. 

 

So how to check the working of this project? Would like to know what this project is all about and its performance in action.

 

Where can I run the project if not in browser? 

Best Regards,
Vishal Shah

**Comment by githubvishalshah** [comment]
Hi kerwinang2016,

 

Can you please update here.

Best Regards,
Vishal Shah

**Comment by githubvishalshah** [comment]
So how to check the working of this project? Would like to know what this project is all about and its performance in action.

Where can I run the project if not in browser?

@fluppyBot @kerwinang2016 @kerwinang

**Comment by kerwinang2016** [comment]
This project was not completed and cannot be run.

**Comment by githubvishalshah** [comment]
Okay, Thanks.
